// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: api.proto

/*
Package api is a generated blademaster stub package.
This code was generated with kratos/tool/protobuf/protoc-gen-bm v0.1.

package 命名使用 {appid}.{version} 的方式, version 形如 v1, v2 ..

It is generated from these files:
	api.proto
*/
package api

import (
	"context"

	bm "github.com/bilibili/kratos/pkg/net/http/blademaster"
	"github.com/bilibili/kratos/pkg/net/http/blademaster/binding"
)
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

var PathClientPing = "/client.service.v1.Client/Ping"
var PathClientSayHello = "/client.service.v1.Client/SayHello"
var PathClientSayHelloURL = "/kratos-demo/say_hello"

// ClientBMServer is the server API for Client service.
type ClientBMServer interface {
	Ping(ctx context.Context, req *google_protobuf1.Empty) (resp *google_protobuf1.Empty, err error)

	SayHello(ctx context.Context, req *HelloReq) (resp *google_protobuf1.Empty, err error)

	SayHelloURL(ctx context.Context, req *HelloReq) (resp *HelloResp, err error)
}

var ClientSvc ClientBMServer

func clientPing(c *bm.Context) {
	p := new(google_protobuf1.Empty)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := ClientSvc.Ping(c, p)
	c.JSON(resp, err)
}

func clientSayHello(c *bm.Context) {
	p := new(HelloReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := ClientSvc.SayHello(c, p)
	c.JSON(resp, err)
}

func clientSayHelloURL(c *bm.Context) {
	p := new(HelloReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := ClientSvc.SayHelloURL(c, p)
	c.JSON(resp, err)
}

// RegisterClientBMServer Register the blademaster route
func RegisterClientBMServer(e *bm.Engine, server ClientBMServer) {
	ClientSvc = server
	e.GET("/client.service.v1.Client/Ping", clientPing)
	e.GET("/client.service.v1.Client/SayHello", clientSayHello)
	e.GET("/kratos-demo/say_hello", clientSayHelloURL)
}
